spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root

  jpa:
    #выводит тела запросов к БД в консоль
    show-sql: true
    generate-ddl: false
    hibernate.ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /docs

rsa:
  private-key:
    certificates/private.pem
  public-key:
    certificates/public.pem



logging:
  file:
    name: application.log

server:
  servlet:
    context-path: "/"